export const ACHIEVEMENT_STATS = Object.freeze([
  { apiName: 'STAT_GAMES_PLAYED', type: 'INT', displayName: 'Games Played' },
  { apiName: 'STAT_GAMES_WON', type: 'INT', displayName: 'Games Won' },
  { apiName: 'STAT_HARD_WINS', type: 'INT', displayName: 'Hard Wins' },
  { apiName: 'STAT_WIN_STREAK', type: 'INT', displayName: 'Current Win Streak' },
  { apiName: 'STAT_FASTEST_WIN_SECONDS', type: 'INT', displayName: 'Fastest Win Seconds' },
  { apiName: 'STAT_SUMMONS_TOTAL', type: 'INT', displayName: 'Total Summons' },
  { apiName: 'STAT_CAPTURES_TOTAL', type: 'INT', displayName: 'Total Captures' },
  { apiName: 'STAT_PROMOTIONS_TOTAL', type: 'INT', displayName: 'Total Promotions' },
  { apiName: 'STAT_CHECKS_GIVEN', type: 'INT', displayName: 'Checks Given' },
]);

export const STEAM_ACHIEVEMENTS = Object.freeze([
  {
    id: 'tutorial_complete',
    apiName: 'ACH_TUTORIAL_COMPLETE',
    nameKo: '소환술 입문',
    nameEn: 'Summoner Initiate',
    descriptionKo: '튜토리얼을 끝까지 완료하세요.',
    descriptionEn: 'Complete the tutorial.',
    trigger: 'tutorial completes',
    stat: null,
    scope: 'single',
    releasePhase: 1,
    iconHint: 'Open spellbook with a pawn mark',
  },
  {
    id: 'first_summon',
    apiName: 'ACH_FIRST_SUMMON',
    nameKo: '첫 소환',
    nameEn: 'First Summon',
    descriptionKo: '처음으로 말을 소환하세요.',
    descriptionEn: 'Summon a piece for the first time.',
    trigger: 'player summon succeeds',
    stat: 'STAT_SUMMONS_TOTAL',
    scope: 'single',
    releasePhase: 1,
    iconHint: 'Emerald summoning circle',
  },
  {
    id: 'first_capture',
    apiName: 'ACH_FIRST_CAPTURE',
    nameKo: '첫 전리품',
    nameEn: 'First Trophy',
    descriptionKo: '처음으로 적 말을 처치하세요.',
    descriptionEn: 'Capture an enemy piece for the first time.',
    trigger: 'player capture succeeds',
    stat: 'STAT_CAPTURES_TOTAL',
    scope: 'single',
    releasePhase: 1,
    iconHint: 'Cracked enemy crown',
  },
  {
    id: 'first_check',
    apiName: 'ACH_FIRST_CHECK',
    nameKo: '왕을 겨누다',
    nameEn: 'King in Sight',
    descriptionKo: '처음으로 체크를 거세요.',
    descriptionEn: 'Give check for the first time.',
    trigger: 'player gives check',
    stat: 'STAT_CHECKS_GIVEN',
    scope: 'single',
    releasePhase: 1,
    iconHint: 'Warning ring around a king',
  },
  {
    id: 'first_promotion',
    apiName: 'ACH_FIRST_PROMOTION',
    nameKo: '승급의 빛',
    nameEn: 'Light of Promotion',
    descriptionKo: '처음으로 병사를 승급시키세요.',
    descriptionEn: 'Promote a pawn for the first time.',
    trigger: 'player pawn promotes',
    stat: 'STAT_PROMOTIONS_TOTAL',
    scope: 'single',
    releasePhase: 1,
    iconHint: 'Pawn rising into queen silhouette',
  },
  {
    id: 'first_win',
    apiName: 'ACH_FIRST_WIN',
    nameKo: '첫 승리',
    nameEn: 'First Victory',
    descriptionKo: '첫 승리를 달성하세요.',
    descriptionEn: 'Win your first match.',
    trigger: 'player wins any single-player match',
    stat: 'STAT_GAMES_WON',
    scope: 'single',
    releasePhase: 1,
    iconHint: 'Gold laurel over the board',
  },
  {
    id: 'easy_win',
    apiName: 'ACH_EASY_WIN',
    nameKo: '시야를 밝히는 자',
    nameEn: 'Bright-Eyed Tactician',
    descriptionKo: '쉬움 난이도에서 승리하세요.',
    descriptionEn: 'Win on Easy difficulty.',
    trigger: 'player wins EASY',
    stat: 'STAT_GAMES_WON',
    scope: 'single',
    releasePhase: 1,
    iconHint: 'Lit board tiles',
  },
  {
    id: 'medium_win',
    apiName: 'ACH_MEDIUM_WIN',
    nameKo: '전장의 균형',
    nameEn: 'Balance of Battle',
    descriptionKo: '보통 난이도에서 승리하세요.',
    descriptionEn: 'Win on Medium difficulty.',
    trigger: 'player wins MEDIUM',
    stat: 'STAT_GAMES_WON',
    scope: 'single',
    releasePhase: 1,
    iconHint: 'Balanced scales and chess board',
  },
  {
    id: 'hard_win',
    apiName: 'ACH_HARD_WIN',
    nameKo: '어려움 정복',
    nameEn: 'Hard Mode Conqueror',
    descriptionKo: '어려움 난이도에서 승리하세요.',
    descriptionEn: 'Win on Hard difficulty.',
    trigger: 'player wins HARD',
    stat: 'STAT_HARD_WINS',
    scope: 'single',
    releasePhase: 1,
    iconHint: 'Crimson crown shattered',
  },
  {
    id: 'fast_win',
    apiName: 'ACH_FAST_WIN',
    nameKo: '3분의 지휘관',
    nameEn: 'Three-Minute Commander',
    descriptionKo: '승리 시 남은 시간이 60초 이상이 되게 하세요.',
    descriptionEn: 'Win with at least 60 seconds remaining.',
    trigger: 'player wins with 60+ seconds remaining',
    stat: 'STAT_FASTEST_WIN_SECONDS',
    scope: 'single',
    releasePhase: 1,
    iconHint: 'Hourglass with a gold crown',
  },
  {
    id: 'win_streak_3',
    apiName: 'ACH_WIN_STREAK_3',
    nameKo: '세 번의 흐름',
    nameEn: 'Threefold Momentum',
    descriptionKo: '3연승을 달성하세요.',
    descriptionEn: 'Win three matches in a row.',
    trigger: 'STAT_WIN_STREAK reaches 3',
    stat: 'STAT_WIN_STREAK',
    scope: 'single',
    releasePhase: 1,
    iconHint: 'Three linked victory seals',
  },
  {
    id: 'summon_all_piece_types',
    apiName: 'ACH_SUMMON_ALL_PIECE_TYPES',
    nameKo: '완성된 소환진',
    nameEn: 'Complete Summoning Circle',
    descriptionKo: '한 판에서 기사, 주교, 룩, 여왕을 모두 소환하세요.',
    descriptionEn: 'Summon a knight, bishop, rook, and queen in one match.',
    trigger: 'player summons knight, bishop, rook, and queen in one match',
    stat: null,
    scope: 'single',
    releasePhase: 1,
    iconHint: 'Four piece sigils around an emerald circle',
  },
]);

export function getAchievementById(id) {
  return STEAM_ACHIEVEMENTS.find(achievement => achievement.id === id);
}
