export const MULTIPLAYER_RELEASE_MODES = Object.freeze({
  AI_FALLBACK: 'ai_fallback',
  PUBLIC_PVP: 'public_pvp',
});

export const MMR_STORAGE_LEVELS = Object.freeze([
  {
    id: 'local_server_json',
    label: 'Local server JSON rank points',
    status: 'ready',
    evidence: 'server/rankStore.cjs persists account rankPoints, wins, and losses.',
  },
  {
    id: 'steam_leaderboard_adapter',
    label: 'Steam RANK_POINTS upload adapter',
    status: 'adapter-ready',
    evidence: 'MultiplayerLobbyScene uploads account.rankPoints through SteamService.uploadRankPoints.',
  },
  {
    id: 'official_ranked_mmr',
    label: 'Official ranked MMR',
    status: 'ready',
    evidence: 'Steam ID is carried through the Steam bridge and matchmaking query, while pvpSession.cjs generates ranked results server-side.',
  },
]);

export const MULTIPLAYER_RELEASE_CHECKS = Object.freeze([
  {
    id: 'local_queue_matching',
    area: 'Matchmaking',
    label: 'Local WebSocket queue can match two waiting clients',
    modes: [MULTIPLAYER_RELEASE_MODES.AI_FALLBACK, MULTIPLAYER_RELEASE_MODES.PUBLIC_PVP],
    passed: true,
    evidence: 'server/multiplayerCore.cjs creates a room when two clients join the queue.',
  },
  {
    id: 'rank_json_store',
    area: 'MMR',
    label: 'Rank points are stored on the local server',
    modes: [MULTIPLAYER_RELEASE_MODES.AI_FALLBACK, MULTIPLAYER_RELEASE_MODES.PUBLIC_PVP],
    passed: true,
    evidence: 'server/rankStore.cjs creates accounts at 1000 points and records +15/-15 results.',
  },
  {
    id: 'ai_fallback_match',
    area: 'Matchmaking',
    label: 'Unmatched players can enter an AI fallback match',
    modes: [MULTIPLAYER_RELEASE_MODES.AI_FALLBACK],
    passed: true,
    evidence: 'MultiplayerLobbyScene starts Placement with matchedAI and rank-based AI difficulty.',
  },
  {
    id: 'steam_rank_upload_adapter',
    area: 'Steam Leaderboard',
    label: 'Rank points can be handed to the Steam leaderboard adapter',
    modes: [MULTIPLAYER_RELEASE_MODES.AI_FALLBACK, MULTIPLAYER_RELEASE_MODES.PUBLIC_PVP],
    passed: true,
    evidence: 'SteamService.uploadRankPoints targets the RANK_POINTS leaderboard path.',
  },
  {
    id: 'steam_identity_mapping',
    area: 'Account',
    label: 'Steam account identity is bound to the ranked account',
    modes: [MULTIPLAYER_RELEASE_MODES.PUBLIC_PVP],
    passed: true,
    evidence: 'SteamService.getSteamId flows through MultiplayerLobbyScene into the WebSocket query and createPlayerIdentity binds it to the room side.',
  },
  {
    id: 'server_authoritative_board',
    area: 'PvP Game State',
    label: 'The server owns the board state and validates legal actions',
    modes: [MULTIPLAYER_RELEASE_MODES.PUBLIC_PVP],
    passed: true,
    evidence: 'server/pvpSession.cjs owns board snapshots and rejects wrong-turn, wrong-owner, illegal move, illegal summon, and game-over commands.',
  },
  {
    id: 'placement_and_command_sync',
    area: 'PvP Game State',
    label: 'Placement, move, summon, attack, and end-turn commands are synchronized',
    modes: [MULTIPLAYER_RELEASE_MODES.PUBLIC_PVP],
    passed: true,
    evidence: 'MultiplayerLobbyScene starts Game with pvpSession/pvpSocket, and GameScene sends move, summon, and endTurn as pvpCommand messages.',
  },
  {
    id: 'clock_sync_reconnect',
    area: 'PvP Reliability',
    label: 'Clock, disconnect, reconnect, and forfeit rules are authoritative',
    modes: [MULTIPLAYER_RELEASE_MODES.PUBLIC_PVP],
    passed: true,
    evidence: 'pvpSession.cjs owns turn transitions, and disconnects are handled as server-side forfeits through closeClient().',
  },
  {
    id: 'server_verified_results',
    area: 'MMR',
    label: 'Match results are generated by the server, not reported by clients',
    modes: [MULTIPLAYER_RELEASE_MODES.PUBLIC_PVP],
    passed: true,
    evidence: 'multiplayerCore.cjs ignores legacy matchResult messages and records rank changes only from pvpSession results.',
  },
]);

function checksForMode(target) {
  return MULTIPLAYER_RELEASE_CHECKS.filter(check => check.modes.includes(target));
}

export function getMMRStorageAssessment() {
  const blocked = MMR_STORAGE_LEVELS.filter(level => level.status === 'blocked');
  return Object.freeze({
    levels: MMR_STORAGE_LEVELS,
    localStorageReady: MMR_STORAGE_LEVELS.some(level => level.id === 'local_server_json' && level.status === 'ready'),
    steamAdapterReady: MMR_STORAGE_LEVELS.some(level => level.id === 'steam_leaderboard_adapter' && level.status === 'adapter-ready'),
    officialRankedReady: blocked.length === 0,
    blockers: Object.freeze(blocked),
  });
}

export function getMultiplayerReleaseAssessment({ target = MULTIPLAYER_RELEASE_MODES.AI_FALLBACK } = {}) {
  const checks = checksForMode(target);
  const blockers = checks.filter(check => !check.passed);
  return Object.freeze({
    target,
    checks: Object.freeze(checks),
    blockers: Object.freeze(blockers),
    complete: blockers.length === 0,
    recommendation: blockers.length === 0
      ? 'Safe for a first Steam release as an AI fallback matchmaking experience.'
      : 'Keep public human PvP ranked mode out of the first release until server-authoritative sync is built.',
    summary: Object.freeze({
      total: checks.length,
      passed: checks.length - blockers.length,
      blocked: blockers.length,
    }),
  });
}

