export const STEAM_STORE_ASSET_SOURCE_URL = 'https://partner.steamgames.com/doc/store/assets';

export const STEAM_STORE_ASSETS = Object.freeze([
  {
    id: 'header_capsule',
    name: 'Header Capsule',
    group: 'store',
    width: 920,
    height: 430,
    required: true,
    format: 'jpg/png',
    usage: 'Steam store page header capsule',
  },
  {
    id: 'small_capsule',
    name: 'Small Capsule',
    group: 'store',
    width: 462,
    height: 174,
    required: true,
    format: 'jpg/png',
    usage: 'Small store capsule placements',
  },
  {
    id: 'main_capsule',
    name: 'Main Capsule',
    group: 'store',
    width: 1232,
    height: 706,
    required: true,
    format: 'jpg/png',
    usage: 'Primary store capsule artwork',
  },
  {
    id: 'vertical_capsule',
    name: 'Vertical Capsule',
    group: 'store',
    width: 748,
    height: 896,
    required: true,
    format: 'jpg/png',
    usage: 'Vertical discovery capsule artwork',
  },
  {
    id: 'screenshots',
    name: 'Screenshots',
    group: 'store',
    minWidth: 1920,
    minHeight: 1080,
    ratio: '16:9',
    required: true,
    format: 'jpg/png',
    usage: 'Store screenshot carousel',
  },
  {
    id: 'shortcut_icon',
    name: 'Shortcut Icon',
    group: 'community_client',
    width: 256,
    height: 256,
    required: true,
    format: 'ico/png',
    usage: 'Shortcut and client icon',
  },
  {
    id: 'app_icon',
    name: 'App Icon',
    group: 'community_client',
    width: 184,
    height: 184,
    required: true,
    format: 'jpg',
    usage: 'Steam app icon',
  },
  {
    id: 'library_capsule',
    name: 'Library Capsule',
    group: 'library',
    width: 600,
    height: 900,
    required: true,
    format: 'jpg/png',
    usage: 'Steam library capsule',
  },
  {
    id: 'library_hero',
    name: 'Library Hero',
    group: 'library',
    width: 3840,
    height: 1240,
    required: true,
    format: 'png',
    usage: 'Steam library hero background',
  },
  {
    id: 'library_logo',
    name: 'Library Logo',
    group: 'library',
    minWidth: 1280,
    minHeight: 720,
    required: true,
    format: 'png',
    usage: 'Transparent logo displayed over the library hero',
  },
  {
    id: 'library_header_capsule',
    name: 'Library Header Capsule',
    group: 'library',
    width: 920,
    height: 430,
    required: true,
    format: 'jpg/png',
    usage: 'Steam library header capsule',
  },
  {
    id: 'page_background',
    name: 'Page Background',
    group: 'store',
    width: 1438,
    height: 810,
    required: false,
    format: 'jpg/png',
    usage: 'Optional subtle store page background',
  },
]);

export function getRequiredSteamStoreAssets() {
  return STEAM_STORE_ASSETS.filter(asset => asset.required);
}

export function getSteamStoreAssetById(id) {
  return STEAM_STORE_ASSETS.find(asset => asset.id === id);
}
